# Конфигурация golangci-lint для проекта Lapidar Discord Bot

run:
  # Таймаут для всех линтеров
  timeout: 5m
  # Включить все линтеры по умолчанию
  tests: true
  # Не запускать линтеры на сгенерированных файлах
  skip-dirs:
    - vendor

# Настройки вывода
output:
  # Формат вывода: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number
  # Печатать строки кода с проблемами
  print-issued-lines: true
  # Печатать линтер, который нашел проблему
  print-linter-name: true

# Настройки линтеров
linters:
  enable:
    - errcheck      # Проверка обработки ошибок
    - gosimple      # Упрощение кода
    - govet         # Анализ кода на ошибки
    - ineffassign   # Обнаружение неиспользуемых присваиваний
    - staticcheck   # Статический анализ
    - typecheck     # Проверка типов
    - unused        # Обнаружение неиспользуемого кода
    - gofmt         # Проверка форматирования
    - goimports     # Проверка импортов
  disable:
    - dupl          # Отключаем поиск дублирующегося кода
    - lll           # Отключаем проверку длины строк

# Настройки проверок
issues:
  # Максимальное количество проблем с одинаковым текстом
  max-same-issues: 3
  # Исключить проблемы для определенных путей
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Игнорировать необработанные ошибки в тестах