# Конфигурация golangci-lint для проекта Lapidar Discord Bot

run:
  # Таймаут для всех линтеров
  timeout: 5m
  # Включить все линтеры по умолчанию
  tests: true
  # Не запускать линтеры на сгенерированных файлах
  # Устаревшая опция skip-dirs заменена на exclude-dirs в секции issues

# Настройки вывода
output:
  # Формат вывода: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # Устаревшая опция format заменена на formats
  formats:
    - format: colored-line-number
  # Печатать строки кода с проблемами
  print-issued-lines: true
  # Печатать линтер, который нашел проблему
  print-linter-name: true

# Настройки линтеров
linters:
  # Включаем нужные линтеры
  enable:
    - errcheck      # Проверка обработки ошибок
    - gosimple      # Упрощение кода
    - govet         # Анализ кода на ошибки
    - ineffassign   # Обнаружение неиспользуемых присваиваний
    - staticcheck   # Статический анализ
    - typecheck     # Проверка типов
    - unused        # Обнаружение неиспользуемого кода
    - gofmt         # Проверка форматирования
    - goimports     # Проверка импортов
  # Отключаем ненужные линтеры
  disable-all: false
  disable:
    - dupl          # Отключаем поиск дублирующегося кода
    - lll           # Отключаем проверку длины строк

# Настройки проверок
issues:
  # Максимальное количество проблем с одинаковым текстом
  max-same-issues: 3
  # Исключить директории из проверки (перенесено из run.skip-dirs)
  exclude-dirs:
    - vendor
  # Исключить проблемы для определенных путей
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck  # Игнорировать необработанные ошибки в тестах
    # Исключения для обработки ошибок в веб-интерфейсе
    - path: web/api\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    - path: web/web_server\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    # Исключения для обработки ошибок в обработчиках
    - path: handlers/handlers\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    - path: handlers/voice_handler\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    # Исключения для неиспользуемых переменных
    - path: web/web_server\.go
      text: "var .* is unused"
      linters:
        - unused
    # Исключения для избыточных символов новой строки
    - path: (web/api\.go|web/web_server\.go|main\.go)
      text: "fmt.Println arg list ends with redundant newline"
      linters:
        - govet